Repository oomck/oomck-bot, pull requests merged in 2021-03, with the labels that each got.

#11 Moving the current project plan into an md file
  planning/project_plan.md
Labels: documentation

#10 Input parsing
  main.py
  requirements.txt
  stop.txt
  text_parser.py
Labels: enhancement

#5 Update README
  README.md
Labels: documentation

#13 Query Api Call and Basic Bot Function
  bot.py
  main.py
  stop.txt
  text_parser.py
  utils/load_data.py
Labels: enhancement

#16 Edit build runs to better interact with Jira
  .github/workflows/tests.yaml
Labels: enhancement

#15 Added list of limitations (v1.0)
  planning/Project Plan Document.pdf
Labels: documentation

#18 Documentation updates
  README.md
  documentation/Gantt Chart.pdf
  documentation/Project Plan Document.pdf
  documentation/Sample Output.txt
  documentation/WBS - WBS gantt chart template.pdf
  documentation/diagrams/high-level-software-structure.png
  es/es.py
  main.py
  planning/Project Plan Document.pdf
  planning/project_plan.md
Labels: documentation, enhancement
